### ISSUE TITLE
Cannot resolve gulp not found on system

### ISSUE THREAD

**Issue by easytechlr** [iliakan/javascript-tutorial-server#10]
Cannot find gulp even after installing with root acess (npm install -g bunyan gulp). The file path exist but the when I run ./edit en or/ ./edit ru it display ./node_modules/.bin/gulp: not found

**Comment by iliakan** [comment]
From what dir you run it?

Please check: does the file `./node_modules/.bin/gulp` in fact exist or not?

**Comment by mkal1375** [comment]
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

**Comment by iliakan** [comment]
WARN does not equal ERROR.
