### ISSUE TITLE
English server not running 

### ISSUE THREAD

**Issue by thesurya** [iliakan/javascript-tutorial-server#14]
6.Run the site
Run the site with the same language. Above we cloned ru tutorial, so:
cd /js/javascript-tutorial-server
./edit ru

so while reaching this step 

for English language 
I executed 
cd /js/javascript-tutorial-server
./edit en 

but it shows "  sh: 1: ./node_modules/.bin/gulp: not found  " 

OS : ubuntu 18.04 
NodeJS : v8.10.0

**Comment by iliakan** [comment]
Did you follow the install instruction from Readme?

**Comment by thesurya** [comment]
Yes, all the steps as mentioned.

**Comment by iliakan** [comment]
This means that gulp module is not installed: `sh: 1: ./node_modules/.bin/gulp: not found "`

Oh you have Node 8. The npm version 5.6.0 is terribly buggy there. Please update npm (`npm up -g`) or Node.JS to 10, remove all `node_modules` and reinstall.
