### ISSUE TITLE
./node_modules/.bin/gulp

### ISSUE THREAD

**Issue by ode22** [iliakan/javascript-tutorial-server#23]
Hi
I run:
 "./edit en"
And get:
sh: ./node_modules/.bin/gulp: No such file or directory

My system is Mac OS 10.14.3
Installed node with nvm
Node version: 11.10.0
nvm version: 0.34.0

**Comment by iliakan** [comment]
Does that file exists or not?

**Comment by ode22** [comment]
I installed node with nvm so that it's on:
~/.nvm/versions/node/v11.10.0/lib/node_modules/gulp

**Comment by iliakan** [comment]
It can't find a local module.

Did you do npm install?

**Comment by ode22** [comment]
I did "nvm install node", "nvm use node"

**Comment by iliakan** [comment]
That's not enough, read the instruction.

**Comment by ode22** [comment]
Did a regular node installation (not nvm)
gulp is installed on /usr/local/lib/node_modules not on the local directory as the command suggests. Should it be copied to the local directory?

**Comment by iliakan** [comment]
Please go to the tutorial server directory and run `npm install` in it.

**Comment by ode22** [comment]
Works. Thanks!
