### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mihirchronicles** [iliakan/javascript-tutorial-server#8]
I am getting this error while I run to execute the code

'worker:client:webpack' errored
Error: ENOENT: no such file or directory, open '..../js/javascript-tutorial-server/tmp/styles.styl'

Gulp error details
Error: ENOENT: no such file or directory, open '..../js/javascript-tutorial-server/tmp/styles.styl'
Error in plugin 'll'

(node:16057) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16061) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:80

**Comment by mihirchronicles** [comment]
Hey, can someone direct me, please? When I execute the code I get a gulp error saying : 

`Gulp error details [ 'ENOTDIR: not a directory, open \'/Users/js/javascript-tutorial-server/tmp/styles.styl\'',`

**Comment by iliakan** [comment]
Did you make npm install?
